-- File Name: ddl_function.sql
-- Purpose: YashanDB Get FUNCTION DDL via DBMS_METADATA
-- Created: 20260814 by huangtingzhong
--
-- Notes:
--   1) Uses DBMS_METADATA.GET_DDL('FUNCTION', name, schema); supported on 23.5.
--   2) YashanDB dba_objects.object_type for functions is often UDF (not FUNCTION).
--   3) DDL type string is still 'FUNCTION' (passed via variable; literal may raise YAS-05319).
--   4) GET_DDL returns CLOB without trailing semicolon; this script appends ';'.
--
-- Usage: ytop -f ddl_function.sql
-- Example: owner=SYS funcname=<function_name>

SET SERVEROUTPUT ON

PROMPT
PROMPT +------------------------------------------------------------------------+
PROMPT | Get FUNCTION DDL (DBMS_METADATA.GET_DDL)                               |
PROMPT +------------------------------------------------------------------------+
PROMPT

ACCEPT owner PROMPT 'Enter owner (schema username): '
ACCEPT funcname PROMPT 'Enter funcname (function name): '

DECLARE
  v_owner VARCHAR2(128) := UPPER(TRIM('&&owner'));
  v_name  VARCHAR2(128) := UPPER(TRIM('&&funcname'));
  v_type  VARCHAR2(32) := 'FUNCTION';
  v_ddl   CLOB;
  v_len   PLS_INTEGER;
  v_off   PLS_INTEGER;
  v_amt   PLS_INTEGER;
  v_cnt   PLS_INTEGER;
  c_chunk CONSTANT PLS_INTEGER := 30000;
BEGIN
  DBMS_OUTPUT.ENABLE(10000000);

  IF v_owner IS NULL OR v_name IS NULL THEN
    DBMS_OUTPUT.PUT_LINE('-- ERROR: owner and funcname are required');
    RETURN;
  END IF;

  SELECT COUNT(*)
    INTO v_cnt
    FROM dba_objects
   WHERE owner = v_owner
     AND object_name = v_name
     AND object_type IN ('FUNCTION', 'UDF');

  IF v_cnt = 0 THEN
    DBMS_OUTPUT.PUT_LINE('-- ERROR: function not found: ' || v_owner || '.' || v_name);
    RETURN;
  END IF;

  v_ddl := DBMS_METADATA.GET_DDL(v_type, v_name, v_owner);
  v_len := NVL(DBMS_LOB.GETLENGTH(v_ddl), 0);

  DBMS_OUTPUT.PUT_LINE('-- Generated by ddl_function.sql');
  DBMS_OUTPUT.PUT_LINE('-- function=' || v_owner || '.' || v_name || '  bytes=' || v_len);
  DBMS_OUTPUT.PUT_LINE('');

  IF v_len = 0 THEN
    DBMS_OUTPUT.PUT_LINE('-- ERROR: empty DDL from DBMS_METADATA.GET_DDL');
    RETURN;
  END IF;

  v_off := 1;
  WHILE v_off <= v_len LOOP
    v_amt := LEAST(c_chunk, v_len - v_off + 1);
    DBMS_OUTPUT.PUT(DBMS_LOB.SUBSTR(v_ddl, v_amt, v_off));
    v_off := v_off + v_amt;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(';');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('-- ERROR: ' || SQLERRM);
END;
/
