-- File Name: ddl_profile.sql
-- Purpose: Generate CREATE PROFILE DDL from dictionary views
-- Created: 20260814 by huangtingzhong
--
-- Notes:
--   1) DBMS_METADATA.GET_DDL('PROFILE') is NOT supported on YashanDB 23.5
--      (YAS-05319); DDL is reconstructed from DBA_PROFILES.
--   2) Empty profile_name => all profiles; explicit name => that profile only.
--   3) Only emits LIMIT clauses where LIMIT <> 'DEFAULT'.
--
-- Usage: ytop -f ddl_profile.sql
-- Example: profile_name=DEFAULT   or TMP_YTOP_DDL_PROF

SET SERVEROUTPUT ON

PROMPT
PROMPT +------------------------------------------------------------------------+
PROMPT | Generate PROFILE DDL (dictionary reconstruct)                          |
PROMPT +------------------------------------------------------------------------+
PROMPT

ACCEPT profile_name PROMPT 'Enter profile_name (empty=all profiles): '

DECLARE
  v_filter VARCHAR2(128) := NULLIF(UPPER(TRIM('&&profile_name')), '');
  v_cnt    PLS_INTEGER := 0;
  v_sql    VARCHAR2(32767);
  v_n      PLS_INTEGER;

  PROCEDURE put(p_line VARCHAR2) IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(p_line);
  END;

  PROCEDURE emit_profile(p_profile VARCHAR2) IS
  BEGIN
    v_sql := 'CREATE PROFILE "' || p_profile || '" LIMIT';
    v_n := 0;
    FOR r IN (
      SELECT resource_name, limit
        FROM dba_profiles
       WHERE profile = p_profile
         AND UPPER(NVL(limit, 'DEFAULT')) <> 'DEFAULT'
       ORDER BY resource_type, resource_name
    ) LOOP
      IF v_n = 0 THEN
        v_sql := v_sql || ' ' || r.resource_name || ' ' || r.limit;
      ELSE
        v_sql := v_sql || CHR(10) || '  ' || r.resource_name || ' ' || r.limit;
      END IF;
      v_n := v_n + 1;
    END LOOP;

    IF v_n = 0 THEN
      put('-- WARN: profile ' || p_profile || ' has only DEFAULT limits; emit minimal LIMIT');
      put('CREATE PROFILE "' || p_profile || '" LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;');
    ELSE
      put(v_sql || ';');
    END IF;
    put('');
  END;
BEGIN
  DBMS_OUTPUT.ENABLE(10000000);
  put('-- Generated by ddl_profile.sql');
  put('-- filter=' || NVL(v_filter, '<all profiles>'));
  put('');

  IF v_filter IS NOT NULL THEN
    SELECT COUNT(*) INTO v_cnt FROM dba_profiles WHERE profile = v_filter AND ROWNUM = 1;
    IF v_cnt = 0 THEN
      put('-- ERROR: profile not found: ' || v_filter);
      RETURN;
    END IF;
    emit_profile(v_filter);
    v_cnt := 1;
  ELSE
    v_cnt := 0;
    FOR r IN (
      SELECT DISTINCT profile FROM dba_profiles ORDER BY profile
    ) LOOP
      emit_profile(r.profile);
      v_cnt := v_cnt + 1;
    END LOOP;
  END IF;

  IF v_cnt = 0 THEN
    put('-- no matching profile');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    put('-- ERROR: ' || SQLERRM);
END;
/
