-- File Name: ddl_synonym.sql
-- Purpose: Generate CREATE SYNONYM DDL from dictionary views
-- Created: 20260814 by huangtingzhong
--
-- Notes:
--   1) DBMS_METADATA.GET_DDL('SYNONYM') is NOT supported on YashanDB 23.5
--      (YAS-05319); DDL is reconstructed from DBA_SYNONYMS.
--   2) owner required (use PUBLIC for public synonyms); synonymname empty =>
--      all synonyms for that owner with DATABASE_MAINTAINED = 'N' (or NULL).
--   3) DB_LINK appended as @link when present.
--
-- Usage: ytop -f ddl_synonym.sql
-- Example: owner=PUBLIC synonymname=ALL_ACS

SET SERVEROUTPUT ON

PROMPT
PROMPT +------------------------------------------------------------------------+
PROMPT | Generate SYNONYM DDL (dictionary reconstruct)                          |
PROMPT +------------------------------------------------------------------------+
PROMPT

ACCEPT owner PROMPT 'Enter owner (schema or PUBLIC, required): '
ACCEPT synonymname PROMPT 'Enter synonymname (empty=all non-maintained in owner): '

DECLARE
  v_owner  VARCHAR2(128) := UPPER(TRIM('&&owner'));
  v_filter VARCHAR2(128) := NULLIF(UPPER(TRIM('&&synonymname')), '');
  v_cnt    PLS_INTEGER := 0;
  v_ddl    VARCHAR2(4000);

  PROCEDURE put(p_line VARCHAR2) IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(p_line);
  END;

  PROCEDURE emit_syn(
    p_owner   IN VARCHAR2,
    p_name    IN VARCHAR2,
    p_towner  IN VARCHAR2,
    p_tname   IN VARCHAR2,
    p_dblink  IN VARCHAR2
  ) IS
    v_target VARCHAR2(512);
  BEGIN
    v_target := '"' || p_towner || '"."' || p_tname || '"';
    IF p_dblink IS NOT NULL THEN
      v_target := v_target || '@"' || p_dblink || '"';
    END IF;

    IF p_owner = 'PUBLIC' THEN
      v_ddl := 'CREATE OR REPLACE PUBLIC SYNONYM "' || p_name || '" FOR ' || v_target;
    ELSE
      v_ddl := 'CREATE OR REPLACE SYNONYM "' || p_owner || '"."' || p_name || '" FOR ' || v_target;
    END IF;
    put(v_ddl || ';');
    put('');
  END;
BEGIN
  DBMS_OUTPUT.ENABLE(10000000);

  IF v_owner IS NULL THEN
    put('-- ERROR: owner is required');
    RETURN;
  END IF;

  put('-- Generated by ddl_synonym.sql');
  put('-- owner=' || v_owner || '  filter=' || NVL(v_filter, '<all non-maintained>'));
  put('');

  IF v_filter IS NOT NULL THEN
    FOR r IN (
      SELECT owner, synonym_name, table_owner, table_name, db_link
        FROM dba_synonyms
       WHERE owner = v_owner
         AND synonym_name = v_filter
    ) LOOP
      emit_syn(r.owner, r.synonym_name, r.table_owner, r.table_name, r.db_link);
      v_cnt := v_cnt + 1;
    END LOOP;
  ELSE
    FOR r IN (
      SELECT owner, synonym_name, table_owner, table_name, db_link
        FROM dba_synonyms
       WHERE owner = v_owner
         AND NVL(database_maintained, 'N') = 'N'
       ORDER BY synonym_name
    ) LOOP
      emit_syn(r.owner, r.synonym_name, r.table_owner, r.table_name, r.db_link);
      v_cnt := v_cnt + 1;
    END LOOP;
  END IF;

  IF v_cnt = 0 THEN
    put('-- no matching synonym');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    put('-- ERROR: ' || SQLERRM);
END;
/
