-- File Name: ddl_dblink.sql
-- Purpose: Generate CREATE DATABASE LINK DDL from dictionary views
-- Created: 20260814 by huangtingzhong
--
-- Notes:
--   1) DBMS_METADATA.GET_DDL('DB_LINK') is NOT supported on YashanDB 23.5
--      (YAS-05319); DDL is reconstructed from DBA_DB_LINKS + SYS.LINK$.
--   2) owner required (PUBLIC for public links); dblink_name empty => all for owner.
--   3) Password: IDENTIFIED BY VALUES "<hex>" from SYS.LINK$.PASSWORD
--      (double quotes required; verified 23.5 round-trip).
--      If hash missing: plaintext placeholder + WARN (reset after import).
--
-- Usage: ytop -f ddl_dblink.sql
-- Example: owner=SYS dblink_name=TMP_YTOP_DDL_LINK

SET SERVEROUTPUT ON

PROMPT
PROMPT +------------------------------------------------------------------------+
PROMPT | Generate DATABASE LINK DDL (dictionary reconstruct)                    |
PROMPT +------------------------------------------------------------------------+
PROMPT

ACCEPT owner PROMPT 'Enter owner (schema or PUBLIC, required): '
ACCEPT dblink_name PROMPT 'Enter dblink_name (empty=all links for owner): '

DECLARE
  v_owner  VARCHAR2(128) := UPPER(TRIM('&&owner'));
  v_filter VARCHAR2(128) := NULLIF(UPPER(TRIM('&&dblink_name')), '');
  v_cnt    PLS_INTEGER := 0;
  c_pwd_fb CONSTANT VARCHAR2(64) := 'ChangeMe_ResetAfterImport';

  PROCEDURE put(p_line VARCHAR2) IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(p_line);
  END;

  FUNCTION link_password(p_owner VARCHAR2, p_name VARCHAR2) RETURN VARCHAR2 IS
    v_hash VARCHAR2(4000);
  BEGIN
    BEGIN
      SELECT l.password
        INTO v_hash
        FROM sys.link$ l
        JOIN sys.user$ u ON l.owner# = u.user#
       WHERE u.name = p_owner
         AND l.name = p_name;
      RETURN v_hash;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        NULL;
    END;
    -- PUBLIC links may use owner# with no matching USER$.NAME='PUBLIC'
    IF p_owner = 'PUBLIC' THEN
      BEGIN
        SELECT l.password
          INTO v_hash
          FROM sys.link$ l
         WHERE l.name = p_name
           AND NOT EXISTS (
                 SELECT 1 FROM sys.user$ u
                  WHERE u.user# = l.owner# AND u.name <> 'PUBLIC'
               )
           AND ROWNUM = 1;
        RETURN v_hash;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          RETURN NULL;
      END;
    END IF;
    RETURN NULL;
  END;

  PROCEDURE emit_link(
    p_owner    IN VARCHAR2,
    p_name     IN VARCHAR2,
    p_username IN VARCHAR2,
    p_host     IN VARCHAR2
  ) IS
    v_hash VARCHAR2(4000);
    v_sql  VARCHAR2(4000);
  BEGIN
    IF p_owner = 'PUBLIC' THEN
      v_sql := 'CREATE PUBLIC DATABASE LINK "' || p_name || '"';
    ELSE
      v_sql := 'CREATE DATABASE LINK "' || p_owner || '"."' || p_name || '"';
    END IF;

    IF p_username IS NOT NULL THEN
      v_hash := link_password(p_owner, p_name);
      IF v_hash IS NOT NULL AND LENGTH(v_hash) > 0 THEN
        v_sql := v_sql || ' CONNECT TO "' || p_username
              || '" IDENTIFIED BY VALUES "' || v_hash || '"';
      ELSE
        put('-- WARN: no LINK$.PASSWORD hash; using plaintext placeholder, reset after import');
        v_sql := v_sql || ' CONNECT TO "' || p_username
              || '" IDENTIFIED BY "' || c_pwd_fb || '"';
      END IF;
    END IF;

    IF p_host IS NOT NULL THEN
      v_sql := v_sql || ' USING ''' || REPLACE(p_host, '''', '''''') || '''';
    END IF;

    put(v_sql || ';');
    put('');
  END;
BEGIN
  DBMS_OUTPUT.ENABLE(10000000);

  IF v_owner IS NULL THEN
    put('-- ERROR: owner is required');
    RETURN;
  END IF;

  put('-- Generated by ddl_dblink.sql');
  put('-- owner=' || v_owner || '  filter=' || NVL(v_filter, '<all>'));
  put('');

  IF v_filter IS NOT NULL THEN
    FOR r IN (
      SELECT owner, db_link, username, host
        FROM dba_db_links
       WHERE owner = v_owner
         AND db_link = v_filter
    ) LOOP
      emit_link(r.owner, r.db_link, r.username, r.host);
      v_cnt := v_cnt + 1;
    END LOOP;
  ELSE
    FOR r IN (
      SELECT owner, db_link, username, host
        FROM dba_db_links
       WHERE owner = v_owner
       ORDER BY db_link
    ) LOOP
      emit_link(r.owner, r.db_link, r.username, r.host);
      v_cnt := v_cnt + 1;
    END LOOP;
  END IF;

  IF v_cnt = 0 THEN
    put('-- no matching database link');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    put('-- ERROR: ' || SQLERRM);
END;
/
