-- File Name: ddl_role.sql
-- Purpose: Generate CREATE ROLE DDL plus grants from dictionary views
-- Created: 20260814 by huangtingzhong
--
-- Notes:
--   1) DBMS_METADATA.GET_DDL('ROLE') is NOT supported on YashanDB 23.5
--      (YAS-05319); DDL is reconstructed from DBA_ROLES / DBA_*_PRIVS.
--   2) Empty role_name => SYS_MAINTAINED is null/'N' (non-system roles).
--   3) Explicit role_name => that role only (including system ones).
--   4) Emits CREATE ROLE, then role/system/object grants to the role.
--
-- Usage: ytop -f ddl_role.sql
-- Example: role_name=TMP_YTOP_DDL_ROLE   or leave empty for non-system

SET SERVEROUTPUT ON

PROMPT
PROMPT +------------------------------------------------------------------------+
PROMPT | Generate ROLE DDL (dictionary reconstruct)                             |
PROMPT +------------------------------------------------------------------------+
PROMPT

ACCEPT role_name PROMPT 'Enter role_name (empty=all non-system roles): '

DECLARE
  v_filter VARCHAR2(128) := NULLIF(UPPER(TRIM('&&role_name')), '');
  v_cnt    PLS_INTEGER := 0;

  PROCEDURE put(p_line VARCHAR2) IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(p_line);
  END;

  PROCEDURE emit_role(p_role VARCHAR2) IS
    v_exists PLS_INTEGER;
  BEGIN
    SELECT COUNT(*) INTO v_exists FROM dba_roles WHERE role = p_role;
    IF v_exists = 0 THEN
      put('-- ERROR: role not found: ' || p_role);
      put('');
      RETURN;
    END IF;

    put('CREATE ROLE "' || p_role || '";');

    FOR r IN (
      SELECT granted_role, admin_option
        FROM dba_role_privs
       WHERE grantee = p_role
       ORDER BY granted_role
    ) LOOP
      IF UPPER(NVL(r.admin_option, 'N')) IN ('YES', 'Y') THEN
        put('GRANT "' || r.granted_role || '" TO "' || p_role || '" WITH ADMIN OPTION;');
      ELSE
        put('GRANT "' || r.granted_role || '" TO "' || p_role || '";');
      END IF;
    END LOOP;

    FOR p IN (
      SELECT privilege, admin_option
        FROM dba_sys_privs
       WHERE grantee = p_role
       ORDER BY privilege
    ) LOOP
      IF UPPER(NVL(p.admin_option, 'N')) IN ('YES', 'Y') THEN
        put('GRANT ' || p.privilege || ' TO "' || p_role || '" WITH ADMIN OPTION;');
      ELSE
        put('GRANT ' || p.privilege || ' TO "' || p_role || '";');
      END IF;
    END LOOP;

    FOR t IN (
      SELECT owner, table_name, privilege, grantable
        FROM dba_tab_privs
       WHERE grantee = p_role
       ORDER BY owner, table_name, privilege
    ) LOOP
      IF UPPER(NVL(t.grantable, 'N')) IN ('YES', 'Y') THEN
        put('GRANT ' || t.privilege || ' ON "' || t.owner || '"."' || t.table_name
            || '" TO "' || p_role || '" WITH GRANT OPTION;');
      ELSE
        put('GRANT ' || t.privilege || ' ON "' || t.owner || '"."' || t.table_name
            || '" TO "' || p_role || '";');
      END IF;
    END LOOP;

    put('');
  END;
BEGIN
  DBMS_OUTPUT.ENABLE(10000000);
  put('-- Generated by ddl_role.sql');
  put('-- filter=' || NVL(v_filter, '<all non-system SYS_MAINTAINED null/N>'));
  put('');

  IF v_filter IS NOT NULL THEN
    emit_role(v_filter);
    v_cnt := 1;
  ELSE
    FOR r IN (
      SELECT role
        FROM dba_roles
       WHERE NVL(sys_maintained, 'N') = 'N'
       ORDER BY role
    ) LOOP
      emit_role(r.role);
      v_cnt := v_cnt + 1;
    END LOOP;
  END IF;

  IF v_cnt = 0 THEN
    put('-- no matching role');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    put('-- ERROR: ' || SQLERRM);
END;
/
