-- File Name: ddl_sequence.sql
-- Purpose: Generate CREATE SEQUENCE DDL from dictionary views
-- Created: 20260814 by huangtingzhong
--
-- Notes:
--   1) DBMS_METADATA.GET_DDL('SEQUENCE') is NOT supported on YashanDB 23.5
--      (YAS-05319); DDL is reconstructed from DBA_SEQUENCES.
--   2) owner required; sequencename empty => all sequences in that owner
--      with DATABASE_MAINTAINED = 'N' (or NULL).
--   3) START WITH uses LAST_NUMBER (current high-water), not MIN_VALUE.
--
-- Usage: ytop -f ddl_sequence.sql
-- Example: owner=YTH_ZCGL sequencename=ATTACHMENT_ID_SEQ

SET SERVEROUTPUT ON

PROMPT
PROMPT +------------------------------------------------------------------------+
PROMPT | Generate SEQUENCE DDL (dictionary reconstruct)                         |
PROMPT +------------------------------------------------------------------------+
PROMPT

ACCEPT owner PROMPT 'Enter owner (schema username, required): '
ACCEPT sequencename PROMPT 'Enter sequencename (empty=all non-maintained in owner): '

DECLARE
  v_owner  VARCHAR2(128) := UPPER(TRIM('&&owner'));
  v_filter VARCHAR2(128) := NULLIF(UPPER(TRIM('&&sequencename')), '');
  v_cnt    PLS_INTEGER := 0;
  v_ddl    VARCHAR2(4000);

  PROCEDURE put(p_line VARCHAR2) IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(p_line);
  END;

  PROCEDURE emit_seq(
    p_owner IN VARCHAR2,
    p_name  IN VARCHAR2,
    p_inc   IN NUMBER,
    p_min   IN NUMBER,
    p_max   IN NUMBER,
    p_cycle IN VARCHAR2,
    p_order IN VARCHAR2,
    p_cache IN NUMBER,
    p_last  IN NUMBER
  ) IS
  BEGIN
    v_ddl := 'CREATE SEQUENCE "' || p_owner || '"."' || p_name || '"'
          || ' INCREMENT BY ' || TO_CHAR(p_inc)
          || ' START WITH ' || TO_CHAR(NVL(p_last, p_min))
          || ' MAXVALUE ' || TO_CHAR(p_max)
          || ' MINVALUE ' || TO_CHAR(p_min);
    IF UPPER(NVL(p_cycle, 'N')) = 'Y' THEN
      v_ddl := v_ddl || ' CYCLE';
    ELSE
      v_ddl := v_ddl || ' NOCYCLE';
    END IF;
    IF UPPER(NVL(p_order, 'N')) = 'Y' THEN
      v_ddl := v_ddl || ' ORDER';
    ELSE
      v_ddl := v_ddl || ' NOORDER';
    END IF;
    IF NVL(p_cache, 0) = 0 THEN
      v_ddl := v_ddl || ' NOCACHE';
    ELSE
      v_ddl := v_ddl || ' CACHE ' || TO_CHAR(p_cache);
    END IF;
    put(v_ddl || ';');
    put('');
  END;
BEGIN
  DBMS_OUTPUT.ENABLE(10000000);

  IF v_owner IS NULL THEN
    put('-- ERROR: owner is required');
    RETURN;
  END IF;

  put('-- Generated by ddl_sequence.sql');
  put('-- owner=' || v_owner || '  filter=' || NVL(v_filter, '<all non-maintained>'));
  put('');

  IF v_filter IS NOT NULL THEN
    FOR r IN (
      SELECT sequence_owner, sequence_name, increment_by, min_value, max_value,
             cycle_flag, order_flag, cache_size, last_number
        FROM dba_sequences
       WHERE sequence_owner = v_owner
         AND sequence_name = v_filter
    ) LOOP
      emit_seq(r.sequence_owner, r.sequence_name, r.increment_by, r.min_value,
               r.max_value, r.cycle_flag, r.order_flag, r.cache_size, r.last_number);
      v_cnt := v_cnt + 1;
    END LOOP;
  ELSE
    FOR r IN (
      SELECT sequence_owner, sequence_name, increment_by, min_value, max_value,
             cycle_flag, order_flag, cache_size, last_number
        FROM dba_sequences
       WHERE sequence_owner = v_owner
         AND NVL(database_maintained, 'N') = 'N'
       ORDER BY sequence_name
    ) LOOP
      emit_seq(r.sequence_owner, r.sequence_name, r.increment_by, r.min_value,
               r.max_value, r.cycle_flag, r.order_flag, r.cache_size, r.last_number);
      v_cnt := v_cnt + 1;
    END LOOP;
  END IF;

  IF v_cnt = 0 THEN
    put('-- no matching sequence');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    put('-- ERROR: ' || SQLERRM);
END;
/
