-- File Name: ddl_table.sql
-- Purpose: YashanDB Get TABLE plus INDEX and TRIGGER DDL for a table
-- Created: 20260516  by  huangtingzhong
--
-- Notes:
--   1) Uses DBMS_METADATA.GET_DDL for TABLE / INDEX / TRIGGER (supported on 23.5).
--   2) TABLE DDL does not include CONSTRAINT/PRIMARY KEY (Yashan GET_DDL limit).
--   3) Indexes used as PK constraint names are excluded from the INDEX section.
--
-- Usage: ytop -f ddl_table.sql
-- Example: TABLE_OWNER=BIZAPP TABLE_NAME=MIXBATCH_T

SET SERVEROUTPUT ON

PROMPT
PROMPT +------------------------------------------------------------------------+
PROMPT | Get TABLE / INDEX / TRIGGER DDL (DBMS_METADATA.GET_DDL)                |
PROMPT +------------------------------------------------------------------------+
PROMPT
PROMPT Enter TABLE_OWNER (schema username):
PROMPT Enter TABLE_NAME (table name):

DECLARE
  v_owner VARCHAR2(128) := UPPER(TRIM('&&TABLE_OWNER'));
  v_name  VARCHAR2(128) := UPPER(TRIM('&&TABLE_NAME'));
  v_ddl   CLOB;
  v_type  VARCHAR2(32);
  v_len   PLS_INTEGER;
  v_off   PLS_INTEGER;
  v_amt   PLS_INTEGER;
  v_cnt   PLS_INTEGER;
  c_chunk CONSTANT PLS_INTEGER := 30000;

  PROCEDURE put_clob(p_ddl CLOB) IS
  BEGIN
    v_len := NVL(DBMS_LOB.GETLENGTH(p_ddl), 0);
    IF v_len = 0 THEN
      DBMS_OUTPUT.PUT_LINE('-- ERROR: empty DDL');
      RETURN;
    END IF;
    v_off := 1;
    WHILE v_off <= v_len LOOP
      v_amt := LEAST(c_chunk, v_len - v_off + 1);
      DBMS_OUTPUT.PUT(DBMS_LOB.SUBSTR(p_ddl, v_amt, v_off));
      v_off := v_off + v_amt;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(';');
    DBMS_OUTPUT.PUT_LINE('');
  END;
BEGIN
  DBMS_OUTPUT.ENABLE(10000000);

  IF v_owner IS NULL OR v_name IS NULL THEN
    DBMS_OUTPUT.PUT_LINE('-- ERROR: TABLE_OWNER and TABLE_NAME are required');
    RETURN;
  END IF;

  SELECT COUNT(*)
    INTO v_cnt
    FROM dba_objects
   WHERE owner = v_owner
     AND object_name = v_name
     AND object_type = 'TABLE';

  IF v_cnt = 0 THEN
    DBMS_OUTPUT.PUT_LINE('-- ERROR: table not found: ' || v_owner || '.' || v_name);
    RETURN;
  END IF;

  DBMS_OUTPUT.PUT_LINE('-- Generated by ddl_table.sql');
  DBMS_OUTPUT.PUT_LINE('-- table=' || v_owner || '.' || v_name);
  DBMS_OUTPUT.PUT_LINE('-- note: TABLE DDL has no CONSTRAINT/PRIMARY KEY section');
  DBMS_OUTPUT.PUT_LINE('');

  v_type := 'TABLE';
  v_ddl := DBMS_METADATA.GET_DDL(v_type, v_name, v_owner);
  DBMS_OUTPUT.PUT_LINE('-- ===== TABLE =====');
  put_clob(v_ddl);

  FOR r IN (
    SELECT INDEX_NAME, owner
      FROM dba_indexes
     WHERE table_owner = v_owner
       AND table_name = v_name
       AND index_name NOT IN (
             SELECT constraint_name
               FROM dba_constraints
              WHERE owner = v_owner
                AND table_name = v_name
                AND constraint_type = 'P'
                AND constraint_name IS NOT NULL
           )
     ORDER BY index_name
  ) LOOP
    v_type := 'INDEX';
    BEGIN
      v_ddl := DBMS_METADATA.GET_DDL(v_type, r.index_name, r.owner);
      DBMS_OUTPUT.PUT_LINE('-- ===== INDEX ' || r.owner || '.' || r.index_name || ' =====');
      put_clob(v_ddl);
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('-- ERROR INDEX ' || r.owner || '.' || r.index_name || ': ' || SQLERRM);
    END;
  END LOOP;

  FOR r IN (
    SELECT trigger_name, owner
      FROM dba_triggers
     WHERE table_owner = v_owner
       AND table_name = v_name
     ORDER BY trigger_name
  ) LOOP
    v_type := 'TRIGGER';
    BEGIN
      v_ddl := DBMS_METADATA.GET_DDL(v_type, r.trigger_name, r.owner);
      DBMS_OUTPUT.PUT_LINE('-- ===== TRIGGER ' || r.owner || '.' || r.trigger_name || ' =====');
      put_clob(v_ddl);
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('-- ERROR TRIGGER ' || r.owner || '.' || r.trigger_name || ': ' || SQLERRM);
    END;
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('-- ERROR: ' || SQLERRM);
END;
/
